
spring:
  application:
    name: consumers-user

server:
  port: 9001
eureka:

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
          defaultZone: http://localhost:9093/eureka
